### ISSUE TITLE
Strange query behavior

### ISSUE THREAD

**Issue by hotrush** [russross/meddler#16]
```
mysql> SELECT * FROM groups WHERE updated_at < '2016-12-15 22:46:00';
+----+----------+--------------+---------------------+---------------------+
| id | group_id | last_post_id | created_at          | updated_at          |
+----+----------+--------------+---------------------+---------------------+
|  1 | 30179569 |            0 | 0000-00-00 00:00:00 | 2016-12-15 22:00:00 |
+----+----------+--------------+---------------------+---------------------+
1 row in set (0.00 sec)
```

but next code returns zero values

```
err := meddler.QueryAll(c.DB, &groups, "SELECT * FROM groups WHERE updated_at < ?", time.Now().Add(-time.Minute*15).Format("2006-01-02 03:04:05"))
```

and next code returns needed value

```
err := meddler.QueryAll(c.DB, &groups, "SELECT * FROM groups WHERE updated_at > ?", time.Now().Add(-time.Minute*15).Format("2006-01-02 03:04:05"))
```

But it must be `<`, not `>`

**Comment by russross** [comment]
That is odd. Unfortunately, I'm not really developing meddler any more. I have a couple of suggestions, though:

1. Could this be a timezone issue? The time format you are using does not include a time zone, so if the database is using UTC and your code is using local time, you might get weird results. Try using time.Now().UTC().Add(...).Format(...) and see if that fixes it.

2. Try configuring MySQL to log all queries, and then look at the precise query that is being generated. If the problem is a time zone (or something else unexpected like that) you will probably spot it pretty quickly.

3. When comparing times, I usually let the database driver do the work. Just give it the time.Time object and don't bother converting it into a string. For example:

    err := meddler.QueryAll(c.DB, &groups, "SELECT * FROM groups WHERE updated_at < ?", time.Now().Add(-time.Minute*15))

Hope that helps!

**Comment by hotrush** [comment]
found an issue, my bad.
valid format for query: `2006-01-02 15:04:05`
